name: deploy
inputs:
  env_name:   { required: true }
  port:       { required: true }
runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Checkout python-greetings repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop previous instance (ignore error if not running)
      shell: pwsh
      run: pm2 delete greetings-app-${{ inputs.env_name }}
      continue-on-error: true


    - name: Start app with pm2
      shell: pwsh
      run: |
        pm2 start app.py `
          --name  "greetings-app-${{ inputs.env_name }}" `
          -- --port  ${{ inputs.port }}
      working-directory: python-greetings