name: deploy
inputs:
  env_name:   { required: true }
  port:       { required: true }
runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Checkout python-greetings repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop previous instance (ignore error if not running)
      shell: pwsh
      run: pm2 delete greetings-app-${{ inputs.env_name }}
      continue-on-error: true


    - name: Start app with pm2
      shell: pwsh
      run: |
        $py = (Get-Command python  -ErrorAction SilentlyContinue).Source `
           ?? (Get-Command python3 -ErrorAction SilentlyContinue).Source
        if (-not $py) {
          throw "Python executable not found in PATH. \
                 Install Python or add it to PATH, then re-run the job."
        }

        pm2 start app.py `
          --name  "greetings-app-${{ inputs.env_name }}" `
          --interpreter "$py" `
          -- --port  ${{ inputs.port }}
      working-directory: python-greetings