name: run-tests
inputs:
  env_name: { required: true }
runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Checkout test framework repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/course-js-api-framework
        path: api-tests

    - name: Install npm deps
      shell: pwsh
      run: npm install
      working-directory: api-tests

    - name: Execute environment-specific tests
      shell: pwsh
      run: npm run greetings greetings_${{ inputs.env_name }}
      working-directory: api-tests
      
    # that way we can be sure that pm2 runner is exited after tests run
    # that's necesarry, because deploy stage can only get rid of it's env runner,
    # not previously launched with another env name
    - name: Stop PM2 instance (ignore if already gone)
      shell: pwsh
      run: pm2 delete "greetings-app-${{ inputs.env_name }}"
      continue-on-error: true
