name: run-tests
inputs:
  env_name: { required: true }
runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Checkout test framework repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/course-js-api-framework
        path: api-tests

    - name: Install npm deps
      run: npm install
      working-directory: api-tests

    - name: Execute environment-specific tests
      run: npm run greetings greetings_${{ inputs.env_name }}
      working-directory: api-tests
