name: Python Greetings Delivery Pipeline
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  install-pip-deps:
    name: Install pip dependencies
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Installing all required dependencies…
        run: |
             echo "Stage: install-pip-deps"
      - uses: ./.github/actions/install-pip-deps

  deploy-to-dev:
    name: Deploy to dev
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4
      - name: Deploying to dev environment…
        run: |
            echo "Stage: deploy-to-dev"
      - uses: ./.github/actions/deploy
        with:
          env_name: dev
          port: 7001

  tests-on-dev:
    name: Tests on dev
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v4
      - name: Running tests against dev…
        run: |
            echo "Stage: tests-on-dev"
      - uses: ./.github/actions/run-tests
        with:
          env_name: dev

  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "Stage: deploy-to-staging"
      - uses: ./.github/actions/deploy
        with:
          env_name: stg
          port: 7002

  tests-on-staging:
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "Stage: tests-on-staging"
      - uses: ./.github/actions/run-tests
        with:
          env_name: stg

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "Stage: deploy-to-preprod"
      - uses: ./.github/actions/deploy
        with:
          env_name: preprod
          port: 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "Stage: tests-on-preprod"
      - uses: ./.github/actions/run-tests
        with:
          env_name: preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "Stage: deploy-to-prod"
      - uses: ./.github/actions/deploy
        with:
          env_name: prod
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "Stage: tests-on-prod"
      - uses: ./.github/actions/run-tests
        with:
          env_name: prod
